import { useEffect, useState } from 'react';

export interface LineShapeFeature {
  type: 'Feature';
  properties: { route: string };
  geometry: { type: 'LineString'; coordinates: [number, number][] };
}

export interface LineShapeCollection {
  type: 'FeatureCollection';
  features: LineShapeFeature[];
}

// Module-level, not per-hook-instance: both the map's own base overlay and a
// journey screen's route-highlight computation load this same static file,
// so a shared cache/in-flight promise keeps that down to one network fetch
// no matter how many components call this hook at once.
let cache: LineShapeCollection | null = null;
let inFlight: Promise<LineShapeCollection> | null = null;

function load(): Promise<LineShapeCollection> {
  if (cache) return Promise.resolve(cache);
  if (!inFlight) {
    inFlight = fetch('/subway-lines.geojson')
      .then((res) => res.json())
      .then((geojson: LineShapeCollection) => {
        cache = geojson;
        return geojson;
      });
  }
  return inFlight;
}

/**
 * Loads the static subway route geometry generated by
 * scripts/generate-line-shapes.mjs (public/subway-lines.geojson). Route
 * paths never change at runtime, so this is a one-time fetch, not a poll.
 */
export function useLineShapes(): LineShapeCollection | null {
  const [data, setData] = useState<LineShapeCollection | null>(cache);

  useEffect(() => {
    if (cache) return;
    let cancelled = false;
    load()
      .then((geojson) => {
        if (!cancelled) setData(geojson);
      })
      .catch(() => {
        // Missing route overlay is non-critical — the map still works without it.
      });
    return () => {
      cancelled = true;
    };
  }, []);

  return data;
}
