import { useEffect, useState } from 'react';

export interface LineShapeFeature {
  type: 'Feature';
  properties: { route: string };
  geometry: { type: 'LineString'; coordinates: [number, number][] };
}

export interface LineShapeCollection {
  type: 'FeatureCollection';
  features: LineShapeFeature[];
}

/**
 * Loads the static subway route geometry generated by
 * scripts/generate-line-shapes.mjs (public/subway-lines.geojson). Route
 * paths never change at runtime, so this is a one-time fetch, not a poll.
 */
export function useLineShapes(): LineShapeCollection | null {
  const [data, setData] = useState<LineShapeCollection | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetch('/subway-lines.geojson')
      .then((res) => res.json())
      .then((geojson: LineShapeCollection) => {
        if (!cancelled) setData(geojson);
      })
      .catch(() => {
        // Missing route overlay is non-critical — the map still works without it.
      });
    return () => {
      cancelled = true;
    };
  }, []);

  return data;
}
