/**
 * Regenerates src/data/stations.ts from MTA's official "MTA Subway Stations
 * and Complexes" open dataset (data.ny.gov, Socrata id 5f5g-n3cz), which
 * covers every subway/SIR station complex system-wide with a real GTFS
 * stop_id per constituent station and its daytime routes already resolved.
 *
 * This replaces hand-typing stations and guessing their real stop_ids by
 * coordinate-matching (see data/gtfsStatic.ts) — this dataset IS the
 * authoritative mapping.
 *
 * Not part of the build; run manually whenever MTA adds/changes stations:
 *   npx tsx scripts/generate-stations.ts
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const DATASET_URL = 'https://data.ny.gov/resource/5f5g-n3cz.json?$limit=2000';

interface SocrataRow {
  complex_id: string;
  stop_name: string;
  gtfs_stop_ids: string;
  daytime_routes: string;
  latitude: string;
  longitude: string;
  borough: string;
}

interface Station {
  id: string;
  name: string;
  lat: number;
  lon: number;
  lines: string[];
  gtfsStopIds: string[];
  /** MTA's borough code: M, Bk, Bx, Q, or SI. */
  borough: string;
}

function toStation(row: SocrataRow): Station | null {
  const lat = Number(row.latitude);
  const lon = Number(row.longitude);
  const lines = row.daytime_routes.trim().split(/\s+/).filter(Boolean);
  const gtfsStopIds = row.gtfs_stop_ids.split(';').map((s) => s.trim()).filter(Boolean);
  if (!row.complex_id || !Number.isFinite(lat) || !Number.isFinite(lon) || lines.length === 0 || gtfsStopIds.length === 0 || !row.borough) {
    return null;
  }
  return { id: row.complex_id, name: row.stop_name, lat, lon, lines, gtfsStopIds, borough: row.borough };
}

async function main() {
  const res = await fetch(DATASET_URL);
  if (!res.ok) throw new Error(`dataset fetch failed: HTTP ${res.status}`);
  const rows = (await res.json()) as SocrataRow[];

  const stations = rows
    .map(toStation)
    .filter((s): s is Station => s !== null)
    .sort((a, b) => Number(a.id) - Number(b.id));

  const skipped = rows.length - stations.length;
  if (skipped > 0) {
    console.warn(`[generate-stations] skipped ${skipped} row(s) missing required fields`);
  }

  const body = stations
    .map(
      (s) =>
        `  { id: '${s.id}', name: ${JSON.stringify(s.name)}, lat: ${s.lat}, lon: ${s.lon}, lines: ${JSON.stringify(s.lines)}, gtfsStopIds: ${JSON.stringify(s.gtfsStopIds)}, borough: ${JSON.stringify(s.borough)} },`,
    )
    .join('\n');

  const output = `// Generated by scripts/generate-stations.ts from MTA's official "MTA Subway
// Stations and Complexes" dataset (data.ny.gov, Socrata id 5f5g-n3cz).
// Re-run that script to refresh this file — do not hand-edit.
//
// Each entry is one station complex system-wide, with its real GTFS parent
// stop_id(s) (gtfsStopIds) straight from MTA — no coordinate-guessing needed
// to resolve real-time data (see data/gtfsStatic.ts).

export interface Station {
  id: string;
  name: string;
  lat: number;
  lon: number;
  lines: string[];
  /** Real MTA GTFS parent stop_id(s) (no N/S suffix) for this complex, straight from MTA's dataset. */
  gtfsStopIds: string[];
  /** MTA's borough code: M, Bk, Bx, Q, or SI. */
  borough: string;
}

export const STATIONS: Station[] = [
${body}
];

export function stationById(id: string): Station | undefined {
  return STATIONS.find((s) => s.id === id);
}

/**
 * Transfer lookup equivalent to a \`transfers.txt\` join: every other line
 * reachable at the same station complex as \`line\`.
 */
export function connectingLines(stationId: string, line: string): string[] {
  const st = stationById(stationId);
  if (!st) return [];
  return st.lines.filter((l) => l !== line);
}

/** All stations (complexes) that serve a given line, in no particular order. */
export function stationsForLine(line: string): Station[] {
  return STATIONS.filter((s) => s.lines.includes(line));
}
`;

  const outPath = fileURLToPath(new URL('../src/data/stations.ts', import.meta.url));
  writeFileSync(outPath, output);
  console.log(`[generate-stations] wrote ${stations.length} stations to ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
